### ISSUE TITLE
Regression related to "Real concurrent asynchronous tasks"

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#235]
The "Real concurrent asynchronous tasks" functionality (brought by #206) is causing a regression in my application. This is the error I get at worker launch time:

```
Traceback (most recent call last):
  File "/home/nova/.conda/envs/doc_classif/bin/doctype-prediction-worker", line 11, in <module>
    load_entry_point('doctype-prediction-worker', 'console_scripts', 'doctype-prediction-worker')()
  File "/src/classifier/worker/command.py", line 24, in command
    cmd(args)
  File "/src/classifier/worker/command.py", line 66, in _execute_worker
    execute_worker()
  File "/src/classifier/worker/run.py", line 17, in execute
    queues=[settings.PROCRASTINATE_QUEUE_NAME, settings.PROCRASTINATE_HEALTHCHECK_QUEUE_NAME]
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/site-packages/procrastinate/app.py", line 256, in run_worker_async
    await worker.run()
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/site-packages/procrastinate/worker.py", line 98, in run
    for worker_id in range(self.concurrency)
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/site-packages/procrastinate/worker.py", line 111, in single_worker
    job = await self.job_store.fetch_job(self.queues)
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/site-packages/procrastinate/store.py", line 33, in fetch_job
    query=sql.queries["fetch_job"], queues=queues
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/site-packages/procrastinate/aiopg_connector.py", line 29, in wrapped
    return await coro(*args, **kwargs)
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/site-packages/procrastinate/aiopg_connector.py", line 191, in execute_query_one
    pool = await self._get_pool()
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/site-packages/procrastinate/aiopg_connector.py", line 165, in _get_pool
    async with self._lock:
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/home/nova/.conda/envs/doc_classif/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
RuntimeError: Task <Task pending coro=<Worker.single_worker() running at /home/nova/.conda/envs/doc_classif/lib/python3.7/site-packages/procrastinate/worker.py:111> cb=[gather.<locals>._done_callback() at /home/nova/.conda/envs/doc_classif/lib/python3.7/asyncio/tasks.py:691]> got Future <Future pending> attached to a different loop
```

It seems to me that the problem is also related to the `PostgresConnector` constructor, which creates an `asyncio.Lock` object while the event loop hasn't been created yet.

I don't have the issue with 0.7.1; it triggers with 0.8.0.

For testing if I change the code

https://github.com/peopledoc/procrastinate/blob/7f77b07f0996b013d242a25116437ff3e5be67a4/procrastinate/worker.py#L95-L100

by 

```py
    await self.single_worker(worker_id=0)
```

the issue doesn't trigger.

**Comment by elemoine** [comment]
The easiest way to reproduce the issue:

```py
>>> import asyncio                                                                                                                                                                         
>>> import procrastinate                                                                                                                                                                   

>>> app = procrastinate.App(connector=procrastinate.AiopgConnector())
>>> asyncio.run(app.run_worker_async())
…
RuntimeError: Task <Task pending name='Task-3' coro=<Worker.single_worker() running at /home/elemoine/src/procrastinate/procrastinate/worker.py:111> cb=[gather.<locals>._done_callback() at /usr/lib64/python3.8/asyncio/tasks.py:751]> got Future <Future pending> attached to a different loop
```

This code works with 0.7.1.

**Comment by ewjoachim** [comment]
Would this example reproduce in a test ?

**Comment by elemoine** [comment]
Here is a Procrastinate-free example, demonstrating why it works with 0.7.1 and not with 0.8.0:

```py
import asyncio


lock = asyncio.Lock()


async def f():
    async with lock:
        await asyncio.sleep(1)


async def main():
    task = asyncio.ensure_future(f())
    try:
        # Version 1
        return await f()
        # Version 2
        # return await asyncio.gather(f())
    finally:
        task.cancel()


asyncio.run(main())
```

Version 1 works, and Version 2 fails with the `got Future <Future pending> attached to a different loop` error. And I don't quite understand why.

**Comment by ewjoachim** [comment]
The lock does seem associated with the wrong loop:
```
(Pdb) lock
<asyncio.locks.Lock object at 0x7fa48a527be0 [unlocked]>
(Pdb) lock._loop
<_UnixSelectorEventLoop running=False closed=False debug=False>
(Pdb) id(lock._loop)
140344671466016
(Pdb) asyncio.get_running_loop()
<_UnixSelectorEventLoop running=True closed=False debug=False>
(Pdb) id(asyncio.get_running_loop())
140344664052688
```
I have no idea:
- Why that works with v1 and v2
- Why when you remove the return and run both v1 and v2, then v2 doesn't fail

Also, my request was "is there a way we make a non-regression test to not be bitten a 3rd time" ?

**Comment by ewjoachim** [comment]
Ah ok, got the 2nd part. Lock fails when the gather runs at the same time as the ensure_future task, but not elsewhere.

**Comment by ewjoachim** [comment]
Here's another reproducing example:
```python
import asyncio

lock = asyncio.Lock()
print("lock", id(lock._loop))


async def f(arg):
    async with lock:
        print(arg, id(asyncio.get_event_loop()))
        await asyncio.sleep(1)


async def main():
    # task = asyncio.create_task(f("v1"))
    try:
        await asyncio.gather(f("v1"), f("v2"))
    finally:
        # task.cancel()
        pass


asyncio.run(main())
```
