### ISSUE TITLE
3 tests that don't await their awaitables

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/procrastinate#262]
I just noticed that we have 3 warnings for tests that don't listen to their awaitables. Not sure why yet, they might be linked to #254, I think it's possible that we'll need to have `AiopgConnector.__del__` call a pure sync method and not a mixed method (so no wait_closed ?) 

```
tests/unit/test_aiopg_connector.py::test_listen_notify_pool_one_connection
  /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py:88: RuntimeWarning: coroutine 'AiopgConnector.close_async' was never awaited
    self._context.run(self._callback, *self._args)

tests/integration/test_wait_stop.py::test_wait_for_activity_timeout
  /Users/joachim/code/procrastinate/procrastinate/aiopg_connector.py:137: RuntimeWarning: coroutine 'AiopgConnector.close_async' was never awaited
    self._pool_args = self._adapt_pool_args(kwargs, json_loads)

tests/integration/test_wait_stop.py::test_wait_for_activity_stop
  /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/locks.py:244: RuntimeWarning: coroutine 'AiopgConnector.close_async' was never awaited
    self._waiters = collections.deque()

```

**Comment by elemoine** [comment]
Related issue: you cannot call `AiopgConnector.close` (the sync method) while an event loop is already running:

```py
$ python -m asyncio
asyncio REPL 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from procrastinate import AiopgConnector
>>> conn = AiopgConnector(dsn="")
>>> await conn.execute_query_async("SELECT 1")
>>> conn.close()
Traceback (most recent call last):
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib64/python3.8/asyncio/__main__.py", line 34, in callback
    coro = func()
  File "<console>", line 1, in <module>
  File "/home/elemoine/src/procrastinate/procrastinate/utils.py", line 117, in wrapper
    return sync_await(awaitable=awaitable)
  File "/home/elemoine/src/procrastinate/procrastinate/utils.py", line 167, in sync_await
    return loop.run_until_complete(awaitable)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

And this is what I get when doing `del conn` rather than `conn.close()`:

```
>>> del conn
Exception ignored in: <function BaseConnector.__del__ at 0x7f4c5a2ad940>
Traceback (most recent call last):
  File "/home/elemoine/src/procrastinate/procrastinate/connector.py", line 47, in __del__
    self.close()
  File "/home/elemoine/src/procrastinate/procrastinate/utils.py", line 117, in wrapper
    return sync_await(awaitable=awaitable)
  File "/home/elemoine/src/procrastinate/procrastinate/utils.py", line 167, in sync_await
    return loop.run_until_complete(awaitable)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
<console>:1: RuntimeWarning: coroutine 'AiopgConnector.close_async' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by elemoine** [comment]
For now I'd suggest that we revert https://github.com/peopledoc/procrastinate/pull/254/commits/89b86771df210ace18f04d26626a5499c5490b65.

**Comment by ewjoachim** [comment]
I don't. I think we can just make a "classic" sync close that doesn't call the async one, and doesn't call `wait_close`. If this doen't cut it, then we can revert that commit.

**Comment by ewjoachim** [comment]
As seen together:
- Reverting won't help
- aiopg's pool.close is sync but does nothing
- aiopg doesn't provide a sync way of closing all connection, but we can still cheat and do it ourselves
- ... and that's just what we'll do.
