### ISSUE TITLE
The procrastinate worker command fails with procrastinate_demo

### ISSUE THREAD

**Issue by elemoine** [peopledoc/procrastinate#309]
The `procrastinate worker` command fails with the procrastinate_demo app:

```shell
$ export PGHOST=localhost PGUSER=postgres PGPASSWORD=password PGDATABASE=procrastinate
$ export PROCRASTINATE_APP=procrastinate_demo.app.app
$ procrastinate worker
Launching a worker on all queues
INFO:procrastinate.periodic:Registring task procrastinate_demo.tasks.tick to run periodically with cron * * * * * *
INFO:procrastinate.worker.worker:Starting worker on all queues
ERROR:procrastinate.utils:Periodic Deferrer error
Traceback (most recent call last):
  File "/home/elemoine/src/procrastinate/procrastinate/utils.py", line 226, in wrapper
    await awaitable
  File "/home/elemoine/src/procrastinate/procrastinate/periodic.py", line 68, in worker
    await self.defer_jobs(jobs_to_defer=self.get_previous_tasks(at=now))
  File "/home/elemoine/src/procrastinate/procrastinate/periodic.py", line 155, in defer_jobs
    job_id = await self.job_store.defer_periodic_job(
  File "/home/elemoine/src/procrastinate/procrastinate/store.py", line 68, in defer_periodic_job
    result = await self.connector.execute_query_one_async(
  File "/home/elemoine/src/procrastinate/procrastinate/connector.py", line 43, in execute_query_one_async
    raise exceptions.SyncConnectorConfigurationError
procrastinate.exceptions.SyncConnectorConfigurationError: 
    A synchronous connector (probably Psycopg2Connector) was used, but the operation
    needs an asynchronous connector (AiopgConnector). Please check your App
    configuration.
    
Error: 
    A synchronous connector (probably Psycopg2Connector) was used, but the operation
    needs an asynchronous connector (AiopgConnector). Please check your App
    configuration.
```

**Comment by ewjoachim** [comment]
Did we merge something that setup the Psycopg2 connector by default ? I recall we tried to avoid that.

**Comment by elemoine** [comment]
We have this currently in the demo:

```py
import procrastinate

import_paths = ["procrastinate_demo.tasks"]
is_async = False  # set to True to run async demo
if is_async:
    connector_class = procrastinate.AiopgConnector
else:
    connector_class = procrastinate.Psycopg2Connector

app = procrastinate.App(
    connector=connector_class(),
    import_paths=import_paths,
    worker_defaults={"listen_notify": False},
)
app.open()
```

**Comment by elemoine** [comment]
There's something that I don't understand: I thought you removed `listen_notify: False`! (https://github.com/peopledoc/procrastinate/commit/746b8e233386165fa02110b06572a03f3955f8e4)

**Comment by elemoine** [comment]
> There's something that I don't understand: I thought you removed `listen_notify: False`! ([746b8e2](https://github.com/peopledoc/procrastinate/commit/746b8e233386165fa02110b06572a03f3955f8e4))

https://github.com/peopledoc/procrastinate/commit/2df7cc5ceb26295cf94d5cb2e5f6b3dd174850d1#diff-845b0890ea23363d7fbc173f1a9d06a2 reverted your change.
